#!/usr/bin/env python3
"""Build the final report markdown for the geometry-R workflow."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path("outputs/assignment_diffusion_mvp/global_copy_assembly_geometry_r")
ROOT.mkdir(parents=True, exist_ok=True)
report = """# Global copy assembly geometry-R report

This report is a placeholder generated by the implementation-only turn.
It records the intended remote workflow and the expected artifact locations.
"""
(ROOT / "global_copy_assembly_geometry_r_report.md").write_text(report)
(ROOT / "config_audit.json").write_text(json.dumps({"status": "STUB_REPORT_ONLY"}, indent=2))
